Correct script create tag (#97)
Co-authored-by: Hien To <tominhhien97@gmail.com>

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -130,8 +130,28 @@ jobs:
 
     - name: Create and push a new tag
       run: |
-        latest_release=$(curl -s https://api.github.com/repos/ggerganov/llama.cpp/releases/latest | jq -r '.tag_name')
+        # Function to get the latest release tag
+        get_latest_tag() {
+          local retries=0
+          local max_retries=3
+          local tag
+          while [ $retries -lt $max_retries ]; do
+            tag=$(curl -s https://api.github.com/repos/janhq/cortex.llamacpp/releases/latest | jq -r .tag_name)
+            if [ -n "$tag" ] && [ "$tag" != "null" ]; then
+              echo $tag
+              return
+            else
+              let retries++
+              echo "Retrying... ($retries/$max_retries)"
+              sleep 2
+            fi
+          done
+          echo "Failed to fetch latest tag after $max_retries attempts."
+          exit 1
+        }
+
+        LATEST_TAG=$(get_latest_tag)
         date_suffix=$(date +'%d.%m.%y')
-        new_tag="${latest_release}-${date_suffix}"
+        new_tag="${LATEST_TAG}-${date_suffix}"
         git tag $new_tag
         git push origin $new_tag
